"""generate_interventions.py — Double-intervention 2x2 to label knowledge- vs reasoning-limited failures.

Turns the pilot's *proxy* labels (correct-absent-from-pool) into *causal* ground truth by
re-testing each hard question under four conditions and measuring which scaffold unlocks it:

    2x2 design       | -reasoning            | +reasoning (step-by-step scaffold)
    -----------------+-----------------------+-----------------------------------
    -knowledge       | control (plain re-ask)| +reasoning
    +knowledge brief | +knowledge            | +both

Each condition is run R times (independent seeds); recovery rate = P(correct) over the R repeats.

Labeling logic (margin m over control):
    control high            -> stochastic-recoverable (was never a real failure)
    +knowledge unlocks only -> KNOWLEDGE-limited      (facts were missing)
    +reasoning unlocks only -> REASONING-limited      (facts present, mis-combined)
    either alone unlocks    -> both-sufficient
    only +both unlocks      -> interaction (both needed)
    nothing unlocks (+both low) -> hard/unrecoverable  (deep knowledge gap OR systematic reasoning error)

The +knowledge brief is generated by the SAME model in an oracle-informed "tutor" pass that is
shown the correct answer but instructed to write answer-blind domain facts. A leakage filter
rejects/regenerates briefs that name the correct option; briefs are cached to JSONL for manual audit.

Backends: --backend {local,ollama,mock}. `local` = transformers Qwen2.5-14B (matches baseline_v2);
`ollama` = OllamaQwenPipeline; `mock` = offline plumbing test (no model).

All outputs are written incrementally and are safe to interrupt/resume.

Usage
-----
    # 1. Preview the subset only (no model calls):
    python generate_interventions.py --select-only --datasets gpqa mmlu-pro

    # 2. Smoke-test the whole pipeline offline:
    python generate_interventions.py --backend mock --limit 5

    # 3. Real run (GPU), 5 repeats/condition, GPQA correct-absent subset:
    python generate_interventions.py --backend local --model-id Qwen/Qwen2.5-14B-Instruct \
        --datasets gpqa --repeats 5 --require-gpu

    # 4. Ollama (lighter model):
    python generate_interventions.py --backend ollama --model-id qwen2.5:7b-instruct \
        --ollama-host http://localhost:11434 --datasets gpqa --repeats 5

    # 5. Label from existing solve results (no new generation):
    python generate_interventions.py --label-only
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np
import pandas as pd

# Reuse the project's Qwen infrastructure.
HERE = Path(__file__).resolve().parent
NEW_DIR = HERE.parent / "New"
sys.path.insert(0, str(HERE.parent / "docs"))
from qwen_methodology_code import (  # noqa: E402
    DebateQuestion,
    LocalQwenPipeline,
    OllamaQwenPipeline,
    OBJECTIVE_LABELS,
    normalize_answer,
    parse_qwen_turn,
)

# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #
DATASET_FILES = {
    "mmlu-pro": [f"baseline_v2_mmlu-pro_s{s}.xlsx" for s in (7, 17, 42)],
    "gpqa":     [f"baseline_v2_gpqa_s{s}.xlsx" for s in (7, 17, 42)],
}
CONDITIONS = ["control", "knowledge", "reasoning", "both"]
OUT_DIR = HERE / "interventions"
AGENTS = ["Agent1", "Agent2", "Agent3"]

SOLVER_SYSTEM = (
    "You are answering a multiple-choice question as carefully as you can. "
    "Choose the single best option."
)
REASONING_SCAFFOLD = (
    "Work through the problem systematically before answering:\n"
    "1. Restate precisely what the question asks.\n"
    "2. List the key facts, definitions, or principles that bear on it.\n"
    "3. Evaluate each option in turn, stating why it could be right or wrong.\n"
    "4. Eliminate the options that fail.\n"
    "5. Commit to the single best remaining option.\n"
    "Think step by step, then give your final answer.\n\n"
)
TUTOR_SYSTEM = (
    "You are a subject-matter expert writing a neutral background briefing that will help a "
    "student reason about a hard exam question. You know the correct answer, but you must NOT "
    "reveal it or hint at which option is correct."
)


def answer_format_block(labels: tuple[str, ...]) -> str:
    slot = "/".join(labels)
    return (
        "Use exactly this format:\n"
        f"Answer: <{slot}>\n"
        "Confidence: <number from 0 to 1>\n"
        "Explanation: <brief justification>"
    )


# --------------------------------------------------------------------------- #
# Subset selection: correct-absent-from-R1-pool questions
# --------------------------------------------------------------------------- #
def _norm(x):
    return None if pd.isna(x) else str(x).strip().upper()


def parse_options(question_text: str) -> dict[str, str]:
    """Extract {letter: option_text} from an embedded 'A. ...' style question."""
    opts = {}
    for m in re.finditer(r"(?m)^\s*([A-J])[\.\)]\s+(.*\S)\s*$", question_text):
        opts[m.group(1).upper()] = m.group(2).strip()
    return opts


def infer_labels(question_text: str) -> tuple[str, ...]:
    opts = parse_options(question_text)
    if opts:
        return tuple(sorted(opts, key=OBJECTIVE_LABELS.index))
    return tuple("ABCD")


def select_correct_absent(datasets: list[str], absent_mode: str) -> pd.DataFrame:
    """One row per unique question that was correct-absent-from-R1-pool across its seeds.

    absent_mode: 'all' (absent in every seed), 'any', or 'majority'.
    """
    per_q: dict[str, dict] = {}
    seed_absent: dict[str, list[bool]] = defaultdict(list)
    for ds in datasets:
        for fname in DATASET_FILES[ds]:
            path = NEW_DIR / fname
            if not path.exists():
                print(f"  [skip] missing {path}")
                continue
            df = pd.read_excel(path, sheet_name="Debate_Traces")
            for _, r in df.iterrows():
                qno = str(r.get("Question #"))
                correct = _norm(r.get("Correct Answer"))
                r1 = {_norm(r.get(f"R1 {a} Answer")) for a in AGENTS}
                r1.discard(None)
                init_correct = (correct in r1) and (Counter(  # plurality correct?
                    [_norm(r.get(f"R1 {a} Answer")) for a in AGENTS if _norm(r.get(f"R1 {a} Answer"))]
                ).most_common(1)[0][0] == correct)
                absent = correct not in r1
                seed_absent[qno].append(absent)
                if qno not in per_q:
                    per_q[qno] = dict(
                        question_no=qno, dataset=ds,
                        category=r.get("Dataset Category", ""),
                        question=str(r.get("Question")),
                        correct_answer=correct,
                        n_seeds=0, n_absent=0, n_init_correct=0,
                    )
                per_q[qno]["n_seeds"] += 1
                per_q[qno]["n_absent"] += int(absent)
                per_q[qno]["n_init_correct"] += int(bool(init_correct))
    rows = []
    for qno, rec in per_q.items():
        flags = seed_absent[qno]
        if absent_mode == "all":
            keep = all(flags)
        elif absent_mode == "any":
            keep = any(flags)
        else:  # majority
            keep = sum(flags) > len(flags) / 2
        if keep:
            rows.append(rec)
    out = pd.DataFrame(rows).sort_values(["dataset", "question_no"]).reset_index(drop=True)
    return out


# --------------------------------------------------------------------------- #
# Backends
# --------------------------------------------------------------------------- #
class MockPipeline:
    """Offline stand-in: deterministic pseudo-answers for plumbing tests only."""

    def complete(self, messages, seed, max_new_tokens=None, temperature=None):
        content = messages[-1]["content"]
        labels = re.findall(r"Answer: <([A-J/]+)>", content)
        choices = labels[0].split("/") if labels else list("ABCD")
        pick = choices[(seed + len(content)) % len(choices)]
        if "background briefing" in messages[0]["content"].lower():
            return "- Relevant principle one.\n- Relevant principle two.\n- Relevant definition three."
        return f"Answer: {pick}\nConfidence: 0.7\nExplanation: mock reasoning."


def build_pipeline(args):
    if args.backend == "mock":
        return MockPipeline()
    if args.backend == "ollama":
        return OllamaQwenPipeline(
            model_id=args.model_id, host=args.ollama_host,
            temperature=args.temperature, top_p=0.9, max_new_tokens=args.max_new_tokens,
        )
    return LocalQwenPipeline(
        model_id=args.model_id, temperature=args.temperature, top_p=0.9,
        max_new_tokens=args.max_new_tokens, device_map="auto",
        torch_dtype="auto", require_gpu=args.require_gpu,
    )


# --------------------------------------------------------------------------- #
# Knowledge-brief generation (oracle-informed, answer-blind, leak-filtered)
# --------------------------------------------------------------------------- #
def brief_leaks(brief: str, correct_letter: str, options: dict[str, str]) -> bool:
    """True if the brief appears to reveal the answer."""
    low = brief.lower()
    if re.search(r"\b(the\s+)?(correct\s+)?(answer|option|choice)\s+is\b", low):
        return True
    if re.search(rf"\boption\s+{correct_letter}\b", brief, re.IGNORECASE):
        return True
    if re.search(rf"(?<![A-Za-z]){correct_letter}[\.\)]\s", brief):  # "B. " / "B) "
        return True
    correct_text = options.get(correct_letter, "")
    if len(correct_text) >= 12 and correct_text.lower() in low:  # verbatim option leak
        return True
    return False


def generate_brief(llm, q: DebateQuestion, options: dict[str, str], seed: int, max_tries: int = 3):
    """Return (brief, leaked_flag). Regenerates up to max_tries to avoid leakage."""
    user = (
        f"Question:\n{q.question}\n\n"
        f"(For your reference only, the correct answer is {q.correct_answer}.)\n\n"
        "Write 3-6 short factual statements giving the domain knowledge a student needs to work "
        "out the answer themselves. RULES:\n"
        "- Do NOT mention any option letter (A, B, C, ...).\n"
        "- Do NOT say or imply which option is correct.\n"
        "- Do NOT restate or quote any answer option verbatim.\n"
        "- Give only general facts, definitions, formulas, or principles.\n"
        "Output as a bulleted list."
    )
    msgs = [{"role": "system", "content": TUTOR_SYSTEM}, {"role": "user", "content": user}]
    brief = ""
    for t in range(max_tries):
        brief = llm.complete(msgs, seed=seed + t, max_new_tokens=350, temperature=0.5).strip()
        if not brief_leaks(brief, q.correct_answer, options):
            return brief, False
    return brief, True  # keep last attempt but flag it


# --------------------------------------------------------------------------- #
# Solve passes for the four conditions
# --------------------------------------------------------------------------- #
def build_solve_messages(q: DebateQuestion, condition: str, brief: str) -> list[dict]:
    fmt = answer_format_block(q.answer_labels)
    parts = []
    if condition in ("knowledge", "both") and brief:
        parts.append(f"Relevant background information:\n{brief}\n")
    if condition in ("reasoning", "both"):
        parts.append(REASONING_SCAFFOLD)
    parts.append(f"{q.question}\n\n{fmt}")
    return [
        {"role": "system", "content": SOLVER_SYSTEM},
        {"role": "user", "content": "\n".join(parts)},
    ]


def solve_once(llm, q: DebateQuestion, condition: str, brief: str, seed: int):
    msgs = build_solve_messages(q, condition, brief)
    raw = llm.complete(msgs, seed=seed, max_new_tokens=512)
    parsed = parse_qwen_turn(raw, "objective", q.answer_labels, strict=False)
    pred = normalize_answer(str(parsed.get("answer", "")))
    return pred, (pred == q.correct_answer), raw


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #
def load_done(path: Path) -> set:
    done = set()
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            try:
                d = json.loads(line)
                done.add((d["question_no"], d["condition"], d["repeat"]))
            except (json.JSONDecodeError, KeyError):
                continue
    return done


def append_jsonl(path: Path, obj: dict):
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")


def run_generation(args, subset: pd.DataFrame):
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    briefs_path = OUT_DIR / "knowledge_briefs.jsonl"
    results_path = OUT_DIR / "solve_results.jsonl"
    llm = build_pipeline(args)

    # cached briefs
    briefs = {}
    if briefs_path.exists():
        for line in briefs_path.read_text(encoding="utf-8").splitlines():
            d = json.loads(line)
            briefs[d["question_no"]] = d
    done = load_done(results_path)

    subset = subset.head(args.limit) if args.limit else subset
    print(f"Generating interventions for {len(subset)} questions x {len(CONDITIONS)} conditions "
          f"x {args.repeats} repeats  (backend={args.backend}, model={args.model_id})")

    for i, row in subset.reset_index(drop=True).iterrows():
        labels = infer_labels(row["question"])
        options = parse_options(row["question"])
        q = DebateQuestion("objective", row["question_no"], row["question"],
                            row["correct_answer"], labels, row.get("category", ""))
        # brief (once per question)
        if q.question_no not in briefs:
            brief, leaked = generate_brief(llm, q, options, seed=args.seed)
            rec = dict(question_no=q.question_no, dataset=row["dataset"], brief=brief,
                       leaked=leaked, correct_answer=q.correct_answer)
            append_jsonl(briefs_path, rec)
            briefs[q.question_no] = rec
        brief_text = briefs[q.question_no]["brief"]

        for cond in CONDITIONS:
            for rep in range(args.repeats):
                if (q.question_no, cond, rep) in done:
                    continue
                seed = args.seed + 1000 * rep + 13 * CONDITIONS.index(cond)
                pred, correct, raw = solve_once(llm, q, cond, brief_text, seed)
                append_jsonl(results_path, dict(
                    question_no=q.question_no, dataset=row["dataset"], condition=cond,
                    repeat=rep, seed=seed, pred=pred, correct=bool(correct),
                    brief_leaked=briefs[q.question_no]["leaked"],
                    raw=raw[:800],
                ))
        if (i + 1) % 10 == 0:
            print(f"  ...{i + 1}/{len(subset)} questions done", flush=True)
    print(f"Done. Results -> {results_path}")


# --------------------------------------------------------------------------- #
# Labeling
# --------------------------------------------------------------------------- #
def label_question(rates: dict[str, float], margin: float, stoch: float, hard: float) -> str:
    c, k, r, b = (rates.get(x, np.nan) for x in CONDITIONS)
    if c >= stoch:
        return "stochastic-recoverable"
    if (b if not np.isnan(b) else max(k, r)) < hard:
        return "hard/unrecoverable"
    dk, dr = k - c, r - c
    if dk >= margin and dr < margin:
        return "knowledge-limited"
    if dr >= margin and dk < margin:
        return "reasoning-limited"
    if dk >= margin and dr >= margin:
        return "both-sufficient"
    if not np.isnan(b) and (b - max(k, r)) >= margin:
        return "interaction (both needed)"
    return "ambiguous"


def run_labeling(args):
    results_path = OUT_DIR / "solve_results.jsonl"
    if not results_path.exists():
        print(f"No results at {results_path}. Run generation first.")
        return
    rows = [json.loads(l) for l in results_path.read_text(encoding="utf-8").splitlines() if l.strip()]
    df = pd.DataFrame(rows)
    agg = (df.groupby(["question_no", "dataset", "condition"])["correct"]
             .mean().unstack("condition"))
    for c in CONDITIONS:
        if c not in agg.columns:
            agg[c] = np.nan
    leaked = df.groupby("question_no")["brief_leaked"].max()
    agg["brief_leaked"] = agg.index.get_level_values("question_no").map(leaked)
    agg["label"] = agg.apply(
        lambda r: label_question({c: r[c] for c in CONDITIONS}, args.margin, args.stoch, args.hard),
        axis=1)
    agg = agg.reset_index()
    out_csv = OUT_DIR / "intervention_labels.csv"
    agg.to_csv(out_csv, index=False)

    print(f"\nLabeled {len(agg)} questions -> {out_csv}")
    print(f"(margin={args.margin}, stochastic>={args.stoch}, hard<{args.hard}; "
          f"leaked briefs excluded from summary)")
    clean = agg[agg["brief_leaked"] != True]  # noqa: E712
    print("\nrecovery rate by condition (mean over questions, non-leaked briefs):")
    print(clean[CONDITIONS].mean().round(3).to_string())
    print("\nlabel distribution:")
    print(clean.groupby("dataset")["label"].value_counts().to_string())
    n_leak = int((agg["brief_leaked"] == True).sum())  # noqa: E712
    if n_leak:
        print(f"\n[warn] {n_leak} questions had answer-leaking briefs (excluded above); audit "
              f"{OUT_DIR/'knowledge_briefs.jsonl'}")


# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--datasets", nargs="+", default=["gpqa", "mmlu-pro"], choices=list(DATASET_FILES))
    ap.add_argument("--absent-mode", default="all", choices=["all", "any", "majority"],
                    help="keep questions correct-absent in all/any/majority of seeds (default all)")
    ap.add_argument("--backend", default="mock", choices=["local", "ollama", "mock"])
    ap.add_argument("--model-id", default="Qwen/Qwen2.5-14B-Instruct")
    ap.add_argument("--ollama-host", default="http://localhost:11434")
    ap.add_argument("--repeats", type=int, default=5, help="solve passes per condition")
    ap.add_argument("--temperature", type=float, default=0.7)
    ap.add_argument("--max-new-tokens", type=int, default=512)
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--limit", type=int, default=0, help="cap number of questions (0 = all)")
    ap.add_argument("--require-gpu", action="store_true")
    ap.add_argument("--select-only", action="store_true", help="write subset CSV and exit")
    ap.add_argument("--label-only", action="store_true", help="label from existing results and exit")
    # labeling thresholds
    ap.add_argument("--margin", type=float, default=0.34, help="recovery gain over control to call a limit")
    ap.add_argument("--stoch", type=float, default=0.5, help="control rate >= this => stochastic-recoverable")
    ap.add_argument("--hard", type=float, default=0.2, help="best-condition rate < this => hard/unrecoverable")
    args = ap.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if args.label_only:
        run_labeling(args)
        return

    subset = select_correct_absent(args.datasets, args.absent_mode)
    subset_csv = OUT_DIR / "correct_absent_subset.csv"
    subset.to_csv(subset_csv, index=False)
    print(f"Selected {len(subset)} correct-absent questions "
          f"({', '.join(args.datasets)}, absent-mode={args.absent_mode}) -> {subset_csv}")
    print(subset.groupby("dataset").size().to_string())
    if args.select_only:
        return

    run_generation(args, subset)
    run_labeling(args)


if __name__ == "__main__":
    main()
